In [1]:
import numpy as np
a = np.zeros(3)
print(a)
print(type(a))
print(type(a[0]))


[0. 0. 0.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [2]:
z = np.zeros(10)
print(z.shape)
z.shape = (5,2)
print(z)

(10,)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
z = np.ones(10)


In [4]:
z = np.empty(3) #generate empty array of 3 elements

In [5]:
z = np.linspace(2,10 , 20)
print(z)

[ 2.          2.42105263  2.84210526  3.26315789  3.68421053  4.10526316
  4.52631579  4.94736842  5.36842105  5.78947368  6.21052632  6.63157895
  7.05263158  7.47368421  7.89473684  8.31578947  8.73684211  9.15789474
  9.57894737 10.        ]


In [6]:
z = np.array([10,20])
print(z)

[10 20]


In [7]:
a_list = [1,2,3,4,5,6,7]
z = np.array([a_list])
print(z)
print(type(z))
print(type(z[0]))
#?z
?z.shape

[[1 2 3 4 5 6 7]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
np.random.seed(0)
z1 = np.random.randint(10, size = 6)
z1

array([5, 0, 3, 3, 7, 9])

In [9]:
z1[0:2]

array([5, 0])

In [10]:
z1[-1] #last element

9

In [20]:
#Broadcasting

x = np.array([[1, 3] , [3, 5]])
y = np.array([0 , 1])
z = x + y
print(z)

[[1 4]
 [3 6]]


In [21]:
# .sum(axis = n) dimension n is collapsed 
# and all values in the new matrix equal to the sum of the corresponding collapsed values

x = np.array([[1,2,3],[4,5,6]])
print(x)

# Compute sum of all elements; 
print(np.sum(x))

[[1 2 3]
 [4 5 6]]
21


In [22]:
# all the rows(axis=0) are collapsed, summing the columns
print(np.sum(x, axis = 0))
print(np.sum(x, axis = 1)) # all the columns(axis=1) are collapsed, 
                          # summing the rows

[5 7 9]
[ 6 15]
