In [15]:
import numpy as np
import time

a = np.random.randn(1000000)
b = np.random.randn(1000000)
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print("c = " + str(c))

print("Loop multiplication take " + str(1000*(toc - tic)) + " ms")

c = 0

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("c = " + str(c))
print("vetorization multiplication take " + str(1000*(toc - tic)) + " ms")


c = 1387.9784751721952
Loop multiplication take 1252.8395652770996 ms
c = 1387.9784751721816
vetorization multiplication take 2.007007598876953 ms


In [22]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 1.73218614 -0.47674813  3.17883027]
 [-0.13571552 -0.33248691  0.31401645]
 [ 0.3606109   1.08705604 -0.65087531]]
